const LEGACY_CATEGORY_ALIASES: Record<string, string> = {
  "agiz-dis": "agiz-dis-bakim",
  atistirmalik: "supermarket/gida-icecek/atistirmalik",
  babet: "kadin-ayakkabi-sandalet",
  "balik-akvaryum": "akvaryum",
  "bebek-arabasi": "puset-araba",
  "bebek-bakim": "bebek-bakim-urunleri",
  "bebek-giyim": "anne-bebek",
  "bebek-kozmetik": "bebek-bakim-urunleri",
  "bebek-sagligi": "bebek-bakim-urunleri",
  besik: "besik-bebek-yatak",
  biberon: "biberon-emzik",
  "bilgisayar-laptop": "laptop",
  "cilt-bakimi": "kozmetik-bakim",
  "diger-evcil-hayvan": "pet-diger",
  "erkek-ayakkabi": "moda",
  "erkek-bakimi": "erkek-bakim",
  "erkek-bot": "erkek-ayakkabi-bot",
  "erkek-ceket-mont": "erkek-dis-giyim",
  "erkek-giyim": "moda",
  "erkek-gomlek": "erkek-giyim-ust",
  "erkek-pantolon": "erkek-giyim-alt",
  "erkek-sneaker": "erkek-ayakkabi-sneaker",
  "erkek-tisort": "erkek-giyim-ust",
  esofman: "esofman-spor-giyim",
  "film-dizi": "kitap-hobi",
  fitness: "fitness-kondisyon",
  "hirdavat-vida": "hirdavat",
  "hobi-sanat": "kitap-hobi",
  "kadin-ayakkabi": "moda",
  "kadin-bot": "kadin-ayakkabi-bot",
  "kadin-ceket-mont": "kadin-dis-giyim",
  "kadin-giyim": "moda",
  "kadin-kazak": "kadin-giyim-ust",
  "kadin-pantolon": "kadin-giyim-alt",
  "kadin-sandalet": "kadin-ayakkabi-sandalet",
  "kadin-sneaker": "kadin-ayakkabi-sneaker",
  "kadin-tisort-bluz": "kadin-giyim-ust",
  "kahve-cay-makinesi": "kucuk-ev-aletleri",
  "bakliyat-makarna": "supermarket/gida-icecek/bakliyat-makarna",
  "dondurma-tatli": "supermarket/gida-icecek/dondurma-tatli",
  "gida": "supermarket/gida-icecek",
  "gida-icecek": "supermarket/gida-icecek",
  icecek: "supermarket/gida-icecek/icecek",
  kahve: "supermarket/gida-icecek/kahve",
  "kahvalti-kahve": "supermarket/gida-icecek/kahvalti-kahve",
  "konserve-sos": "supermarket/gida-icecek/konserve-sos",
  "supermarket/atistirmalik": "supermarket/gida-icecek/atistirmalik",
  "supermarket/bakliyat-makarna": "supermarket/gida-icecek/bakliyat-makarna",
  "supermarket/dondurma-tatli": "supermarket/gida-icecek/dondurma-tatli",
  "supermarket/gida": "supermarket/gida-icecek",
  "supermarket/icecek": "supermarket/gida-icecek/icecek",
  "supermarket/icecek/kahve": "supermarket/gida-icecek/kahve",
  "supermarket/icecek/kahve/cekirdek-kahve": "supermarket/gida-icecek/kahve/cekirdek-kahve",
  "supermarket/icecek/kahve/espresso-cappucino-kahve": "supermarket/gida-icecek/kahve/espresso-cappucino-kahve",
  "supermarket/icecek/kahve/filtre-cekirdek-kahveler": "supermarket/gida-icecek/kahve/filtre-cekirdek-kahveler",
  "supermarket/icecek/kahve/hazir-kahve": "supermarket/gida-icecek/kahve/hazir-kahve",
  "supermarket/icecek/kahve/kahve-aksesuarlari": "supermarket/gida-icecek/kahve/kahve-aksesuarlari",
  "supermarket/icecek/kahve/kahve-kapsulleri": "supermarket/gida-icecek/kahve/kahve-kapsulleri",
  "supermarket/icecek/kahve/turk-kahvesi": "supermarket/gida-icecek/kahve/turk-kahvesi",
  "supermarket/kahvalti-kahve": "supermarket/gida-icecek/kahvalti-kahve",
  "supermarket/kahve": "supermarket/gida-icecek/kahve",
  "supermarket/kahve/espresso": "supermarket/gida-icecek/kahve/espresso-cappucino-kahve",
  "supermarket/kahve/filtre-kahve": "supermarket/gida-icecek/kahve/filtre-cekirdek-kahveler",
  "supermarket/kahve/nespresso-kapsul": "supermarket/gida-icecek/kahve/kahve-kapsulleri",
  "supermarket/kahve/turk-kahvesi": "supermarket/gida-icecek/kahve/turk-kahvesi",
  "supermarket/konserve-sos": "supermarket/gida-icecek/konserve-sos",
  kus: "kus-urunleri",
  "lastik-jant": "oto-lastik-jant",
  lego: "oyuncak-lego",
  makyaj: "kozmetik-bakim",
  "masa-oyunu": "oyuncak-masa",
  "mobilya-dekorasyon": "ev-yasam",
  "mutfak-aleti": "kucuk-ev-aletleri",
  navigasyon: "oto-navigasyon",
  "ofis-elektronigi": "kirtasiye",
  "ofis-mobilyasi": "mobilya-ofis",
  "oto-teyp": "oto-teyp-multimedya",
  "outdoor-giyim": "spor-outdoor",
  oyuncak: "anne-bebek",
  "pet-bakim": "pet-bakim-hijyen",
  "rc-robot": "oyuncak-rc",
  "sac-bakimi": "sac-bakim",
  "sac-stilizasyon": "sac-kurutma-sekillendirici",
  serum: "serum-ampul",
  "spor-giyim": "spor-outdoor",
  "takim-elbise": "erkek-takim-elbise",
  temizlik: "temizlik-deterjan",
  topuklu: "kadin-ayakkabi-topuklu",
  yoga: "spor-outdoor/fitness/yoga-pilates",
  "yoga-pilates": "spor-outdoor/fitness/yoga-pilates",
  "spor-outdoor/yoga-pilates": "spor-outdoor/fitness/yoga-pilates",
  "spor-outdoor/yoga-pilates/foam-roller": "spor-outdoor/fitness/yoga-pilates/foam-roller",
  "spor-outdoor/yoga-pilates/pilates-mati": "spor-outdoor/fitness/yoga-pilates/pilates-mati",
  "spor-outdoor/yoga-pilates/pilates-topu": "spor-outdoor/fitness/yoga-pilates/pilates-topu",
  "spor-outdoor/yoga-pilates/yoga-bloku": "spor-outdoor/fitness/yoga-pilates/yoga-bloku",
  "spor-outdoor/yoga-pilates/yoga-mati": "spor-outdoor/fitness/yoga-pilates/yoga-mati",
  "spor-outdoor/spor-fitness/fitness-kondisyon/pilates": "spor-outdoor/fitness/yoga-pilates",
  "spor-outdoor/spor-fitness/fitness-kondisyon/pilates/pilates-mati": "spor-outdoor/fitness/yoga-pilates/pilates-mati",
  "yuz-maskesi": "yuz-maskesi-skincare",
  "yuz-temizleme": "yuz-temizleyici",
};

const LEGACY_CATEGORY_QUERY_HINTS: Record<string, string> = {
  "bebek-giyim": "bebek giyim",
  "cilt-bakimi": "cilt bakımı",
  "erkek-ayakkabi": "erkek ayakkabı",
  "erkek-giyim": "erkek giyim",
  "film-dizi": "film dizi",
  "hobi-sanat": "hobi sanat",
  "kadin-ayakkabi": "kadın ayakkabı",
  "kadin-giyim": "kadın giyim",
  "kahve-cay-makinesi": "kahve çay makinesi",
  makyaj: "makyaj",
  "mobilya-dekorasyon": "mobilya dekorasyon",
  "mutfak-aleti": "mutfak aletleri",
  "ofis-elektronigi": "ofis ekipmanı",
  "ofis-mobilyasi": "ofis mobilyası",
  "outdoor-giyim": "outdoor giyim",
  oyuncak: "oyuncak",
  "spor-giyim": "spor giyim",
};

export function resolveCategorySlug(slug: string): string {
  return LEGACY_CATEGORY_ALIASES[slug] ?? slug;
}

export function getCategoryQueryHint(slug: string): string | undefined {
  return LEGACY_CATEGORY_QUERY_HINTS[slug];
}
